module.exports = [
  { name: "Eishin Flash", tier: 3 },
  { name: "Meisho Doto", tier: 3 },
  { name: "Special Week (Summer)", tier: 4 },
  { name: "Maruzensky (Summer)", tier: 4 },
  { name: "Gold City", tier: 3 },
  { name: "Fuji Kiseki", tier: 3 },
  { name: "Grass Wonder (Fantasy)", tier: 4 },
  { name: "El Condor Pasa (Fantasy)", tier: 4 },
  { name: "Hishi Amazon", tier: 3 },
  { name: "Seiun Sky", tier: 3 },
  { name: "Air Groove (Wedding)", tier: 4 },
  { name: "Mayano Top Gun (Wedding)", tier: 4 },
  { name: "Narita Brian", tier: 3 },
  { name: "Smart Falcon", tier: 3 },
  { name: "Narita Taishin", tier: 3 },
  { name: "Curren Chan", tier: 3 },
  { name: "Tokai Teio (Anime Collab)", tier: 4 },
  { name: "Mejiro McQueen (Anime Collab)", tier: 4 },
  { name: "Biwa Hayahide", tier: 3 },
  { name: "Mihono Bourbon", tier: 3 },
  { name: "TM Opera O", tier: 3 },
  { name: "Special Week", tier: 3 },
  { name: "Silence Suzuka", tier: 3 },
  { name: "Tokai Teio", tier: 3 },
  { name: "Maruzensky", tier: 3 },
  { name: "Oguri Cap", tier: 3 },
  { name: "Taiki Shuttle", tier: 3 },
  { name: "Mejiro McQueen", tier: 3 },
  { name: "Symboli Rudolf", tier: 3 },
  { name: "Rice Shower", tier: 3 },
  { name: "Gold Ship", tier: 2 },
  { name: "Vodka", tier: 2 },
  { name: "Daiwa Scarlet", tier: 2 },
  { name: "Grass Wonder", tier: 2 },
  { name: "El Condor Pasa", tier: 2 },
  { name: "Air Groove", tier: 2 },
  { name: "Mayano Top Gun", tier: 2 },
  { name: "Super Creek", tier: 2 },
  { name: "Mejiro Ryan", tier: 1 },
  { name: "Agnes Tachyon", tier: 1 },
  { name: "Winning Ticket", tier: 1 },
  { name: "Sakura Bakushin O", tier: 1 },
  { name: "Haru Urara", tier: 1 },
  { name: "Matikanefukukitaru", tier: 1 },
  { name: "Nice Nature", tier: 1 },
  { name: "King Halo", tier: 1 },
];
