module.exports = [
    { name: "An Giang", aliases: ["an giang"], code: "90000", query: "An Giang, Vietnam" },
    { name: "Bà Rịa - Vũng Tàu", aliases: ["ba ria vung tau", "vung tau"], code: "79000", query: "Vung Tau, Vietnam" },
    { name: "Bắc Giang", aliases: ["bac giang"], code: "22000", query: "Bac Giang, Vietnam" },
    { name: "Bắc Kạn", aliases: ["bac kan"], code: "96000", query: "Bac Kan, Vietnam" },
    { name: "Bạc Liêu", aliases: ["bac lieu"], code: "97000", query: "Bac Lieu, Vietnam" },
    { name: "Bắc Ninh", aliases: ["bac ninh"], code: "24000", query: "Bac Ninh, Vietnam" },
    { name: "Bến Tre", aliases: ["ben tre"], code: "86000", query: "Ben Tre, Vietnam" },
    { name: "Bình Định", aliases: ["binh dinh", "quy nhon"], code: "55000", query: "Quy Nhon, Vietnam" },
    { name: "Bình Dương", aliases: ["binh duong"], code: "75000", query: "Binh Duong, Vietnam" },
    { name: "Bình Phước", aliases: ["binh phuoc"], code: "83000", query: "Binh Phuoc, Vietnam" },
    { name: "Bình Thuận", aliases: ["binh thuan", "phan thiet"], code: "77000", query: "Phan Thiet, Vietnam" },
    { name: "Cà Mau", aliases: ["ca mau"], code: "98000", query: "Ca Mau, Vietnam" },
    { name: "Cần Thơ", aliases: ["can tho"], code: "94000", query: "Can Tho, Vietnam" },
    { name: "Cao Bằng", aliases: ["cao bang"], code: "95000", query: "Cao Bang, Vietnam" },
    { name: "Đà Nẵng", aliases: ["da nang"], code: "50000", query: "Da Nang, Vietnam" },
    { name: "Đắk Lắk", aliases: ["dak lak", "buon ma thuot"], code: "63000", query: "Buon Ma Thuot, Vietnam" },
    { name: "Đắk Nông", aliases: ["dak nong", "gia nghia"], code: "64000", query: "Gia Nghia, Vietnam" },
    { name: "Điện Biên", aliases: ["dien bien"], code: "38000", query: "Dien Bien, Vietnam" },
    { name: "Đồng Nai", aliases: ["dong nai", "bien hoa"], code: "76000", query: "Bien Hoa, Vietnam" },
    { name: "Đồng Tháp", aliases: ["dong thap"], code: "81000", query: "Dong Thap, Vietnam" },
    { name: "Gia Lai", aliases: ["gia lai", "pleiku"], code: "60000", query: "Pleiku, Vietnam" },
    { name: "Hà Giang", aliases: ["ha giang"], code: "31000", query: "Ha Giang, Vietnam" },
    { name: "Hà Nam", aliases: ["ha nam"], code: "40000", query: "Ha Nam, Vietnam" },
    { name: "Hà Nội", aliases: ["ha noi", "hanoi"], code: "10000", query: "Hanoi, Vietnam" },
    { name: "Hà Tĩnh", aliases: ["ha tinh"], code: "48000", query: "Ha Tinh, Vietnam" },
    { name: "Hải Dương", aliases: ["hai duong"], code: "17000", query: "Hai Duong, Vietnam" },
    { name: "Hải Phòng", aliases: ["hai phong"], code: "18000", query: "Hai Phong, Vietnam" },
    { name: "Hậu Giang", aliases: ["hau giang"], code: "91000", query: "Hau Giang, Vietnam" },
    { name: "Hòa Bình", aliases: ["hoa binh"], code: "36000", query: "Hoa Binh, Vietnam" },
    { name: "Hồ Chí Minh", aliases: ["ho chi minh", "hcm", "tphcm", "sai gon"], code: "70000", query: "Ho Chi Minh City, Vietnam" },
    { name: "Hưng Yên", aliases: ["hung yen"], code: "16000", query: "Hung Yen, Vietnam" },
    { name: "Khánh Hòa", aliases: ["khanh hoa", "nha trang"], code: "57000", query: "Nha Trang, Vietnam" },
    { name: "Kiên Giang", aliases: ["kien giang", "phu quoc"], code: "92000", query: "Kien Giang, Vietnam" },
    { name: "Kon Tum", aliases: ["kon tum"], code: "58000", query: "Kon Tum, Vietnam" },
    { name: "Lai Châu", aliases: ["lai chau"], code: "39000", query: "Lai Chau, Vietnam" },
    { name: "Lâm Đồng", aliases: ["lam dong", "da lat"], code: "67000", query: "Da Lat, Vietnam" },
    { name: "Lạng Sơn", aliases: ["lang son"], code: "25000", query: "Lang Son, Vietnam" },
    { name: "Lào Cai", aliases: ["lao cai"], code: "33000", query: "Lao Cai, Vietnam" },
    { name: "Long An", aliases: ["long an"], code: "85000", query: "Long An, Vietnam" },
    { name: "Nam Định", aliases: ["nam dinh"], code: "42000", query: "Nam Dinh, Vietnam" },
    { name: "Nghệ An", aliases: ["nghe an", "vinh"], code: "46000", query: "Vinh, Vietnam" },
    { name: "Ninh Bình", aliases: ["ninh binh"], code: "43000", query: "Ninh Binh, Vietnam" },
    { name: "Ninh Thuận", aliases: ["ninh thuan"], code: "59000", query: "Ninh Thuan, Vietnam" },
    { name: "Phú Thọ", aliases: ["phu tho"], code: "29000", query: "Phu Tho, Vietnam" },
    { name: "Phú Yên", aliases: ["phu yen"], code: "56000", query: "Phu Yen, Vietnam" },
    { name: "Quảng Bình", aliases: ["quang binh"], code: "47000", query: "Quang Binh, Vietnam" },
    { name: "Quảng Nam", aliases: ["quang nam"], code: "51000", query: "Quang Nam, Vietnam" },
    { name: "Quảng Ngãi", aliases: ["quang ngai"], code: "54000", query: "Quang Ngai, Vietnam" },
    { name: "Quảng Ninh", aliases: ["quang ninh", "ha long"], code: "20000", query: "Ha Long, Vietnam" },
    { name: "Quảng Trị", aliases: ["quang tri"], code: "52000", query: "Quang Tri, Vietnam" },
    { name: "Sóc Trăng", aliases: ["soc trang"], code: "99000", query: "Soc Trang, Vietnam" },
    { name: "Sơn La", aliases: ["son la"], code: "37000", query: "Son La, Vietnam" },
    { name: "Tây Ninh", aliases: ["tay ninh"], code: "84000", query: "Tay Ninh, Vietnam" },
    { name: "Thái Bình", aliases: ["thai binh"], code: "41000", query: "Thai Binh, Vietnam" },
    { name: "Thái Nguyên", aliases: ["thai nguyen"], code: "23000", query: "Thai Nguyen, Vietnam" },
    { name: "Thanh Hóa", aliases: ["thanh hoa"], code: "44000", query: "Thanh Hoa, Vietnam" },
    { name: "Thừa Thiên Huế", aliases: ["thua thien hue", "hue"], code: "53000", query: "Hue, Vietnam" },
    { name: "Tiền Giang", aliases: ["tien giang"], code: "82000", query: "Tien Giang, Vietnam" },
    { name: "Trà Vinh", aliases: ["tra vinh"], code: "87000", query: "Tra Vinh, Vietnam" },
    { name: "Tuyên Quang", aliases: ["tuyen quang"], code: "30000", query: "Tuyen Quang, Vietnam" },
    { name: "Vĩnh Long", aliases: ["vinh long"], code: "89000", query: "Vinh Long, Vietnam" },
    { name: "Vĩnh Phúc", aliases: ["vinh phuc"], code: "28000", query: "Vinh Phuc, Vietnam" },
    { name: "Yên Bái", aliases: ["yen bai"], code: "32000", query: "Yen Bai, Vietnam" }
];
