# -------------------------------------- #
#           Bypass Addon Config          #
# -------------------------------------- #

# Get your API key from meobypass.click
api_key: "gBLwQsXhx3Myd1q3zd13"
